### ISSUE TITLE
[BUG]: Problem uploading a HCCAPX

### ISSUE THREAD

**Issue by fdevarennes** [hashtopolis/server#1033]
### Version Information

0.13.1

### Description

Hi,

I'm trying to upload a new hashlist in he HCCAPX format. In the webgui i'm using the hashcat file format, i'm selecting HCCAPX. When i upload the file, i get a ERROR 500 in the web interface.

When i go in the logs, i have this in my logs ;

`Jan 17 09:49:02 hashtopolisweb php: PHP Warning:  Undefined array key 1 in /var/www/hashtopolis/inc/utils/HashlistUtils.class.php on line 944
Jan 17 09:49:02 hashtopolisweb php: PHP Warning:  Undefined array key 2 in /var/www/hashtopolis/inc/utils/HashlistUtils.class.php on line 945
Jan 17 09:49:02 hashtopolisweb php: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\x8F\xD9g\xE7\x85\x06...' for column 'essid' at row 1 in /var/www/hashtopolis/dba/AbstractModelFactory.class.php:115
Jan 17 09:49:02 hashtopolisweb php: Stack trace:
Jan 17 09:49:02 hashtopolisweb php: #0 /var/www/hashtopolis/dba/AbstractModelFactory.class.php(115): PDOStatement->execute()
Jan 17 09:49:02 hashtopolisweb php: #1 /var/www/hashtopolis/dba/models/HashBinaryFactory.class.php(80): DBA\AbstractModelFactory->save()
Jan 17 09:49:02 hashtopolisweb php: #2 /var/www/hashtopolis/inc/utils/HashlistUtils.class.php(954): DBA\HashBinaryFactory->save()
Jan 17 09:49:02 hashtopolisweb php: #3 /var/www/hashtopolis/inc/handlers/HashlistHandler.class.php(94): HashlistUtils::createHashlist()
Jan 17 09:49:02 hashtopolisweb php: #4 /var/www/hashtopolis/hashlists.php(31): HashlistHandler->handle()
Jan 17 09:49:02 hashtopolisweb php: #5 {main}
Jan 17 09:49:02 hashtopolisweb php:   thrown in /var/www/hashtopolis/dba/AbstractModelFactory.class.php on line 115`

I checked the my Collation in the database and it's configured like the documentation says.

What would be the problem?

**Comment by s3inlc** [comment]
Most likely this is an issue with parsing the HCCAPX format, unsure if it is an issue with the file itself or a special case not covered by Hashtopolis.
The HCCAPX format is deprecated, it is recommended to use the new WPA hash format which is in ASCII. Due to this deprecation in the foreseeable future, binary hashes and the special HCCAPX case will likely be removed from Hashtopolis.
