### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'crackers\\11.7z'

### ISSUE THREAD

**Issue by tosiara** [hashtopolis/server#692]
For some unknown reason the downloaded cracker binary got locked which caused the agent to die:
(either antivirus or something was keeping 7za.exe in the process list forever, killing it resolved the issue)
```
Starting client 's3-python-0.6.0.10'...
Collecting agent data...
Login successful!
Hashtopolis Server version: 0.12.0 (commit 0e9047b branch master)
Client is up-to-date!
Got task with id: 63
Traceback (most recent call last):
  File "C:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "hashtopolis.zip\__main__.py", line 343, in <module>
  File "hashtopolis.zip\__main__.py", line 174, in loop
  File "hashtopolis.zip\htpclient\binarydownload.py", line 194, in check_version
  File "hashtopolis.zip\htpclient\download.py", line 27, in download
PermissionError: [Errno 13] Permission denied: 'crackers\\11.7z'
```
Probably it would be better to log error and disable agent or keep trying until the server issues a task with another cracker

**Comment by zyronix** [comment]
Merged into #884
