### ISSUE TITLE
Adding new cracker version fails

### ISSUE THREAD

**Issue by Knuust** [hashtopolis/server#718]
Hi everyone,
i just tried to supply the new hashcat version 6.2.2 to my clients by upload the .7z file to "files" on the server and add the binary with the url to to crackers.

Now I try to start a client working on a new task with the updated cracker:

```
C:\Program Files\hashcat-client>py hashtopolis.zip
Found existing lock.pid, checking if python process is running...
Ignoring lock.pid file because PID is not existent anymore or not running python!
Starting client 's3-python-0.6.0.10'...
Collecting agent data...
Login successful!
Hashtopolis Server version: 0.12.0 (commit a247df9 branch master)
Client is up-to-date!
Got task with id: 13534
Downloading: [==================================================]

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: crackers\2.7z

Error: Can not open file as archive

Downloading: [==================================================]
Client is up-to-date!
Got cracker binary type hashcat
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\hashcat-client\hashtopolis.zip\__main__.py", line 343, in <module>
  File "C:\Program Files\hashcat-client\hashtopolis.zip\__main__.py", line 198, in loop
  File "C:\Program Files\hashcat-client\hashtopolis.zip\htpclient\hashcat_cracker.py", line 46, in __init__
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig
```
It seems, that 7z can't open the archive, right?
I downloaded the archive from the binaries section from official hashcat website.

Do you have any idea about the problem here?

Thank you in advance,
knuust

**Comment by s3inlc** [comment]
Hi, could you please try to reproduce the error when running the agent with the debug flag enabled? This could yield better information about what exactly goes wrong.

Based on the error text I would guess it's not the issue that it can't open the 7z, but something in the path of the folder makes it crashing.

**Comment by s3inlc** [comment]
Another option would be to check if there is any error message in the downloaded 7z file (crackers\2.7z), i.e. if there is an error on download, it will just put it into the file (which then obviously is not a valid 7z archive).

**Comment by Knuust** [comment]
Hi!
Thank you for your help.
I tried to start the client with --debug:

```
C:\Program Files\hashcat-client>py hashtopolis.zip --debug
Found existing lock.pid, checking if python process is running...
Ignoring lock.pid file because PID is not existent anymore or not running python!
Starting client 's3-python-0.6.0.10'...
Collecting agent data...
{'action': 'updateInformation', 'token': 'uwFZxYlrLR', 'uid': '3e9cf996-f496-448a-a2bd-33cad77504f5', 'os': 1, 'devices': ['Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz', 'NVIDIA GeForce GTX 1050']}
Starting new HTTP connection (1): 192.168.100.109:80
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 51
b'{"action":"updateInformation","response":"SUCCESS"}'
{'action': 'login', 'token': 'uwFZxYlrLR', 'clientSignature': 's3-python-0.6.0.10'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 134
b'{"action":"login","response":"SUCCESS","multicastEnabled":false,"timeout":30,"server-version":"0.12.0 (commit a247df9 branch master)"}'
Login successful!
Hashtopolis Server version: 0.12.0 (commit a247df9 branch master)
{'action': 'checkClientVersion', 'token': 'uwFZxYlrLR', 'version': '0.6.0.10', 'type': 'python'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 67
b'{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}'
Client is up-to-date!
Entering loop...
{'action': 'getFileStatus', 'token': 'uwFZxYlrLR'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 190
b'{"action":"getFileStatus","response":"SUCCESS","filenames":["Pre-cracked_16_12-10-2020_11-23-29.txt","SKYECC.txt","Sky-ECC_sm.txt","Sky-ECC_sm(old).txt","Sky-ECC-stealth_mode-alphabet.txt"]}'
{'action': 'getTask', 'token': 'uwFZxYlrLR'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 369
b'{"action":"getTask","response":"SUCCESS","taskId":13534,"attackcmd":"#HL# -a-a-a-a-a-a","cmdpars":" --hash-type=13761 ","hashlistId":63,"bench":30,"statustimer":5,"files":[],"crackerId":"2","benchType":"speed","hashlistAlias":"#HL#","keyspace":"0","usePreprocessor":false,"preprocessor":"0","preprocessorCommand":"","enforcePipe":false,"slowHash":true,"useBrain":false}'
Got task with id: 13534
{'action': 'downloadBinary', 'token': 'uwFZxYlrLR', 'type': 'cracker', 'binaryVersionId': '2'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 147
b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/192.168.100.109\\/getFile.php?file=17","name":"hashcat","executable":"hashcat.exe"}'
Starting new HTTPS connection (1): 192.168.100.109:443
Download error: HTTPSConnectionPool(host='192.168.100.109', port=443): Max retries exceeded with url: /getFile.php?file=17 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000285C663B0A0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))
Download of cracker binary failed!
```

You guessed correctly, unzipping the 7z file is not the problem.

**Comment by Knuust** [comment]
Euh, I just saw I got the wrong port. Now with the correct one:

```
py hashtopolis.zip --debug
Found existing lock.pid, checking if python process is running...
Ignoring lock.pid file because PID is not existent anymore or not running python!
Starting client 's3-python-0.6.0.10'...
Collecting agent data...
{'action': 'updateInformation', 'token': 'uwFZxYlrLR', 'uid': '3e9cf996-f496-448a-a2bd-33cad77504f5', 'os': 1, 'devices': ['Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz', 'NVIDIA GeForce GTX 1050']}
Starting new HTTP connection (1): 192.168.100.109:80
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 51
b'{"action":"updateInformation","response":"SUCCESS"}'
{'action': 'login', 'token': 'uwFZxYlrLR', 'clientSignature': 's3-python-0.6.0.10'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 134
b'{"action":"login","response":"SUCCESS","multicastEnabled":false,"timeout":30,"server-version":"0.12.0 (commit a247df9 branch master)"}'
Login successful!
Hashtopolis Server version: 0.12.0 (commit a247df9 branch master)
{'action': 'checkClientVersion', 'token': 'uwFZxYlrLR', 'version': '0.6.0.10', 'type': 'python'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 67
b'{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}'
Client is up-to-date!
Entering loop...
{'action': 'getFileStatus', 'token': 'uwFZxYlrLR'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 212
b'{"action":"getFileStatus","response":"SUCCESS","filenames":["Pre-cracked_16_12-10-2020_11-23-29.txt","SKYECC.txt","Sky-ECC_sm.txt","Sky-ECC_sm(old).txt","Sky-ECC-stealth_mode-alphabet.txt","rockyou_1_60.hcmask"]}'
{'action': 'getTask', 'token': 'uwFZxYlrLR'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 362
b'{"action":"getTask","response":"SUCCESS","taskId":19341,"attackcmd":"-a 3 #HL# ","cmdpars":" --hash-type=13711 ","hashlistId":17,"bench":30,"statustimer":5,"files":[],"crackerId":"3","benchType":"speed","hashlistAlias":"#HL#","keyspace":"0","usePreprocessor":false,"preprocessor":"0","preprocessorCommand":"","enforcePipe":false,"slowHash":true,"useBrain":false}'
Got task with id: 19341
{'action': 'downloadBinary', 'token': 'uwFZxYlrLR', 'type': 'cracker', 'binaryVersionId': '3'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 149
b'{"action":"downloadBinary","response":"SUCCESS","url":"http:\\/\\/192.168.100.109:80\\/getFile.php?file=17","name":"hashcat","executable":"hashcat.exe"}'
http://192.168.100.109:80 "HEAD /getFile.php?file=17 HTTP/1.1" 200 0
http://192.168.100.109:80 "GET /getFile.php?file=17 HTTP/1.1" 200 10
Downloading: [==================================================]

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: crackers\3.7z

Error: Can not open file as archive

{'action': 'getHashlist', 'token': 'uwFZxYlrLR', 'hashlistId': 17}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 99
b'{"action":"getHashlist","response":"SUCCESS","url":"getHashlist.php?hashlists=17&token=uwFZxYlrLR"}'
http://192.168.100.109:80 "GET /getHashlist.php?hashlists=17&token=uwFZxYlrLR HTTP/1.1" 200 512
Downloading: [==================================================]
{'action': 'checkClientVersion', 'token': 'uwFZxYlrLR', 'version': '0.6.0.10', 'type': 'python'}
http://192.168.100.109:80 "POST /api/server.php HTTP/1.1" 200 67
b'{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}'
Client is up-to-date!
Got cracker binary type hashcat
CALL: hashcat64.exe --version
Traceback (most recent call last):
  File "C:\Users\Auswerter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Auswerter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\hashcat-client\hashtopolis.zip\__main__.py", line 343, in <module>
  File "C:\Program Files\hashcat-client\hashtopolis.zip\__main__.py", line 198, in loop
  File "C:\Program Files\hashcat-client\hashtopolis.zip\htpclient\hashcat_cracker.py", line 46, in __init__
  File "C:\Users\Auswerter\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Auswerter\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Auswerter\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Auswerter\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig
```

It seems like the download works, but 7z failed...?

There are no other crackers in the cracker folder after the dowload

**Comment by Knuust** [comment]
OK, i fixed it. The Problem seems to be the authentication of the client. The hashtopolis Server denies the request... I needed to set up a second http Server to provide the 7z. Not the besteht workaround i would guess but it works.

**Comment by mmotwicki** [comment]
Why did you closed it? 
Why the hashtopolis is not handling this request correctly?
