### ISSUE TITLE
[BUG] Fatal Error when deleting last Hashlist

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#888]
Hashtopolis throws an error when deleting the last Hashlist on the Hashlist page. It still gets deleted, but an error is logged.

```
[27-Mar-2023 14:59:18 UTC] PHP Fatal error:  Uncaught PDOException: There is no active transaction in /var/www/html/src/inc/utils/HashlistUtils.class.php:632
2023-03-27 16:59:18 Stack trace:
2023-03-27 16:59:18 #0 /var/www/html/src/inc/utils/HashlistUtils.class.php(632): PDO->commit()
2023-03-27 16:59:18 #1 /var/www/html/src/inc/handlers/HashlistHandler.class.php(69): HashlistUtils::delete('1', Object(DBA\User))
2023-03-27 16:59:18 #2 /var/www/html/src/hashlists.php(31): HashlistHandler->handle('deleteHashlist')
2023-03-27 16:59:18 #3 {main}
2023-03-27 16:59:18   thrown in /var/www/html/src/inc/utils/HashlistUtils.class.php on line 632
```

Steps to reproduce:
- Create one hashlist
- Delete hashlist from the hashlist page

**Comment by s3inlc** [comment]
I guess the TRUNCATE instead of the deletion (which happens if there is only one list left) commits the active transaction automatically, therefore no transaction is active anymore when it tries to commit. 

So, in case this is triggered: https://github.com/hashtopolis/server/blob/master/src/inc/utils/HashlistUtils.class.php#L591 it should not commit at the end of the function. Or we drop this special case and handle it via deletion always.

**Comment by zyronix** [comment]
I went for enabling the transaction again, imo this makes it the state consistent with the rest of the file.
