### ISSUE TITLE
[BUG] Failed to start python agent

### ISSUE THREAD

**Issue by koff75** [hashtopolis/server#939]
I'm using the latest version (agent python and server on Docker).
Docker is working fine on 8080 & 4200 ports. I have redirected the web interface to the host IP to make sure that all the servers can contact the Docker through the VLAN.
As example, 147.16.16.3:8080 is running on a Docker with the IP 172.19.0.1
The IP 147.16.16.100 can get 147:16.16.3:8080
The python agent for Windows is working fine on localhost ;
But when I wanna use another computer on the VLAN, I can register the agent but not more :
```
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xx\Downloads\hashtopolis.zip\__main__.py", line 377, in <module>
  File "C:\Users\xx\Downloads\hashtopolis.zip\__main__.py", line 164, in init
  File "C:\Users\xx\Downloads\hashtopolis.zip\htpclient\initialize.py", line 25, in run
  File "C:\Users\xx\Downloads\hashtopolis.zip\htpclient\initialize.py", line 115, in __update_information
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 120: invalid start byte
```

Any information ?
Thanks :)

**Comment by s3inlc** [comment]
Is your agent windows running with some special locale setting or using non-latin characters in the hostname?

**Comment by koff75** [comment]
Thanks for your quick answer :)
I've checked the Windows settings, and all is set to FR.
The hostname is like this : "BEAAA"
And I checked with Python : 

```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> current_locale = locale.getlocale()
>>> print("Paramètres régionaux actuels :", current_locale)
Paramètres régionaux actuels : ('fr_FR', 'cp1252')
```

**Comment by koff75** [comment]
Oh thanks a lot ! Your command indicates a non-ascii output, and then I decided to change the OS language to English...
By now, the agents are registered and operational. 
Thanks for your reactivity ! =)
